const TODAY=new Date().toLocaleDateString('en-CA');
const turnProcess=()=>[
 {note:'',name:'Tenant Gave Notice',kind:'date',value:''},{note:'',name:'Sent Confirmation',kind:'check',value:false},{note:'',name:'Owner Notified',kind:'check',value:false},{note:'',name:'Move Out',kind:'date',value:''},{note:'',name:'Keys Returned',kind:'date',value:''},{note:'',name:'MOI',kind:'date',value:''},{note:'',name:'Transfer Utilities',kind:'check',value:false},{note:'',name:'Mailed Disposition',kind:'date',value:''},{note:'',name:'PMI',kind:'date',value:''},{note:'',name:'Listed',kind:'date',value:''}
];
const listingProcess=()=>[
 {note:'',name:'Listed',kind:'date',value:''},{note:'',name:'Approval Sent',kind:'date',value:''},{note:'',name:'Accepted',kind:'date',value:''},{note:'',name:'Lease Sent',kind:'date',value:''},{note:'',name:'Utility Form Sent',kind:'date',value:''},{note:'',name:'Signed Lease Received',kind:'date',value:''},{note:'',name:'Utility Form Received',kind:'date',value:''},{note:'',name:'Rent Paid',kind:'check',value:false},{note:'',name:'SD Paid',kind:'check',value:false},{note:'',name:'Remove LB',kind:'check',value:false},{note:'',name:'Key Pickup',kind:'date',value:''},{note:'',name:'Owner Notified',kind:'check',value:false}
];
const seed=[
 {id:1,address:'1350 Swayze',type:'turn',archived:false,notes:'Owner intends to re-rent.',process:turnProcess()},
 {id:2,address:'842 E 9th',type:'turn',archived:false,notes:'',process:turnProcess()},
 {id:3,address:'737 Kenyon',type:'listing',archived:false,notes:'',price:'2200',securityDeposit:'2200',sourceKeysReturned:'2026-08-14',process:listingProcess()},
 {id:4,address:'190 Birchwood',type:'listing',archived:false,notes:'Waiting on signed lease.',price:'',securityDeposit:'',sourceKeysReturned:'',process:listingProcess()}
];
function setVal(x,n,v){const p=x.process.find(p=>p.name===n);if(p)p.value=v}
setVal(seed[0],'Tenant Gave Notice','2026-09-19');setVal(seed[0],'Move Out','2026-10-19');
setVal(seed[1],'Tenant Gave Notice','2026-08-18');setVal(seed[1],'Move Out','2026-09-15');setVal(seed[1],'Keys Returned','2026-09-15');setVal(seed[1],'MOI','2026-09-16');
setVal(seed[2],'Listed','2026-08-28');setVal(seed[3],'Listed','2026-09-03');setVal(seed[3],'Approval Sent','2026-09-16');
let stored=JSON.parse(localStorage.getItem('whiteboardData')||'null');
// v4 migrates old prototype data to the new Listing schema while keeping addresses/notes.
if(stored){stored=stored.map(x=>{x.archived=!!x.archived;(x.process||[]).forEach(p=>{if(typeof p.note!=='string')p.note=''});if(x.type==='turn'){const order=['Tenant Gave Notice','Sent Confirmation','Owner Notified','Move Out','Keys Returned','MOI','Transfer Utilities','Mailed Disposition','PMI','Listed'];x.process.sort((a,b)=>order.indexOf(a.name)-order.indexOf(b.name))}if(x.type==='listing'&&!x.process.some(p=>p.name==='Listed')){const old=x.process||[],fresh=listingProcess();const oldGet=n=>old.find(p=>p.name===n)?.value||'';fresh.find(p=>p.name==='Listed').value=oldGet('Website Listed');fresh.find(p=>p.name==='Approval Sent').value=oldGet('Approval Sent');fresh.find(p=>p.name==='Signed Lease Received').value=oldGet('Signed Lease Received');fresh.find(p=>p.name==='Key Pickup').value=oldGet('Key Pickup');fresh.find(p=>p.name==='Owner Notified').value=oldGet('Owner Notified');x.process=fresh;x.price=x.price||'';x.securityDeposit=x.securityDeposit||'';x.sourceKeysReturned=x.sourceKeysReturned||''}return x})}
let data=stored||seed,openId=null,filter='all';
const $=s=>document.querySelector(s),rows=$('#rows'),filters=$('#filters');
const get=(x,n)=>x.process.find(p=>p.name===n)?.value||'';const short=d=>d?d.slice(5).replace('-','/'):'—';
function diffDays(start,end=TODAY,inclusive=false){if(!start)return 0;const n=Math.round((Date.parse(end)-Date.parse(start))/86400000);return Math.max(inclusive?1:0,n+(inclusive?1:0))}
function state(x){if(x.archived)return'archived';if(x.type==='turn')return get(x,'Keys Returned')&&!get(x,'Mailed Disposition')?'active':'notice';if(get(x,'Signed Lease Received'))return'rented';if(get(x,'Approval Sent')||get(x,'Accepted')||get(x,'Lease Sent'))return'pending';return'listed'}
function turnDays(x){const k=get(x,'Keys Returned');if(!k)return 0;return diffDays(k,get(x,'Mailed Disposition')||TODAY,true)}
function listingDays(x){const d=get(x,'Listed');if(!d)return 0;return diffDays(d,get(x,'Signed Lease Received')||TODAY,false)}
function totalFromKeys(x){return x.sourceKeysReturned?diffDays(x.sourceKeysReturned,get(x,'Key Pickup')||TODAY,false):null}
function save(){localStorage.setItem('whiteboardData',JSON.stringify(data))}
function field(l,v){return `<div class="status-field"><div class="label">${l}</div><div class="value">${v}</div></div>`}
function statusHTML(x){if(x.archived)return field('STATUS','Archived')+field('TYPE',x.type==='turn'?'Turn':'Listing')+'<div></div>';if(x.type==='turn'){if(state(x)==='notice')return field('NOTICE',short(get(x,'Tenant Gave Notice')))+field('MOVE OUT',short(get(x,'Move Out')))+'<div></div>';return field('KEYS RETURNED',short(get(x,'Keys Returned')))+field('MOI',short(get(x,'MOI')))+`<div class="status-field"><div class="label">DAYS</div><div class="turn-days">${turnDays(x)} / 31</div></div>`}const leaseState=state(x),lease=leaseState.toUpperCase(),pickup=get(x,'Key Pickup');return field('LIST DATE',short(get(x,'Listed')))+`<div class="status-field"><div class="label">LEASE STATUS</div><div class="value lease-status ${leaseState}">${lease}</div></div>`+`<div><div class="status-field"><div class="label">DAYS</div><div class="listing-days">${listingDays(x)}</div></div></div>`+(pickup?field('KEY PICKUP',short(pickup)):'')}
function activeData(){return data.filter(x=>!x.archived)}
function renderFilters(){const active=activeData(),c=s=>active.filter(x=>state(x)===s).length,arch=data.filter(x=>x.archived).length;filters.innerHTML=`<button class="filter-btn ${filter==='all'?'active':''}" data-f="all"><b>ALL ${active.length}</b></button><span class="filter-label">TURNS</span><button class="filter-btn ${filter==='notice'?'active':''}" data-f="notice">NOTICES <b>${c('notice')}</b></button><button class="filter-btn ${filter==='active'?'active':''}" data-f="active">ACTIVE <b>${c('active')}</b></button><span class="filter-label">LISTINGS</span><button class="filter-btn ${filter==='listed'?'active':''}" data-f="listed">LISTED <b>${c('listed')}</b></button><button class="filter-btn ${filter==='pending'?'active':''}" data-f="pending">PENDING <b>${c('pending')}</b></button><button class="filter-btn ${filter==='rented'?'active':''}" data-f="rented">RENTED <b>${c('rented')}</b></button><button class="filter-btn archive-filter ${filter==='archived'?'active':''}" data-f="archived">ARCHIVED <b>${arch}</b></button>`;filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{const next=b.dataset.f;filter=(filter===next&&next!=='all')?'all':next;openId=null;render()})}
function render(){renderFilters();const q=$('#search').value.trim().toLowerCase();const list=data.filter(x=>{const matches=!q||x.address.toLowerCase().includes(q);if(!matches)return false;if(q)return true;return filter==='archived'?x.archived:!x.archived&&(filter==='all'||state(x)===filter)});rows.innerHTML=list.length?list.map(x=>`<section class="row ${x.archived?'archived':''} ${openId===x.id?'open':''}" data-id="${x.id}"><div class="row-main"><div class="property">${x.address}</div><div class="type ${x.type==='listing'?'listing':''}">${x.type.toUpperCase()}</div><div class="status">${statusHTML(x)}</div>${x.archived?'<div class="archive-pill">ARCHIVED</div>':'<div class="chev">›</div>'}</div>${openId===x.id?detailsHTML(x):''}</section>`).join(''):`<div class="empty">No processes in this view.</div>`;rows.querySelectorAll('.row-main').forEach(el=>el.onclick=()=>{const id=+el.parentElement.dataset.id;openId=openId===id?null:id;render()});rows.querySelectorAll('.proc-control').forEach(el=>el.onchange=()=>{const x=data.find(y=>y.id===+el.closest('.row').dataset.id),p=x.process[+el.dataset.i];p.value=p.kind==='check'?el.checked:el.value;save();render()});rows.querySelectorAll('.proc-note').forEach(el=>el.oninput=()=>{const x=data.find(y=>y.id===+el.closest('.row').dataset.id),p=x.process[+el.dataset.i];p.note=el.value;save()});rows.querySelectorAll('.notes textarea').forEach(el=>el.oninput=()=>{data.find(y=>y.id===+el.closest('.row').dataset.id).notes=el.value;save()});rows.querySelectorAll('.meta-control').forEach(el=>el.onchange=()=>{const x=data.find(y=>y.id===+el.closest('.row').dataset.id);x[el.dataset.field]=el.value;save();render()});rows.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();handleAction(b.dataset.action,+b.closest('.row').dataset.id)})}
function detailsHTML(x){const process=`<div class="process-head"><div>PROCESS</div><div>STATUS</div><div>NOTE</div></div>${x.process.map((p,i)=>{const groupStart=x.type==='turn'&&['Move Out','Mailed Disposition'].includes(p.name);return `<div class="process-row ${groupStart?'group-start':''}"><div>${p.name}</div><div>${p.kind==='check'?`<label class="check-status"><input class="proc-control" data-i="${i}" type="checkbox" ${p.value?'checked':''}><span>${p.value?'Complete':'Not complete'}</span></label>`:`<input class="proc-control" data-i="${i}" type="date" value="${p.value}">`}</div><div><input class="proc-note" data-i="${i}" type="text" value="${(p.note||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}" placeholder="Add note…"></div></div>`}).join('')}`;const listingMeta=x.type==='listing'?`<div class="listing-meta"><div class="meta-label">Price</div><div><input class="money-input meta-control" data-field="price" inputmode="decimal" placeholder="$" value="${x.price||''}"></div><div class="meta-label">Security Deposit</div><div><input class="money-input meta-control" data-field="securityDeposit" inputmode="decimal" placeholder="$" value="${x.securityDeposit||''}"></div></div>`:'';const metric=x.type==='listing'&&totalFromKeys(x)!==null?`<div class="metrics">Total days from key return: <strong>${totalFromKeys(x)}</strong></div>`:'';let actions='';if(x.archived)actions=`<div class="card-actions"><button class="action-restore" data-action="restore">Restore to Whiteboard</button></div>`;else if(x.type==='turn')actions=`<div class="card-actions"><button class="action-primary" data-action="create-listing">Create Listing & Archive Turn</button><button class="action-secondary" data-action="archive">Archive Turn</button></div>`;else actions=`<div class="card-actions"><button class="action-secondary" data-action="archive">Archive Listing</button></div>`;return `<div class="details">${process}${listingMeta}<div class="notes"><label>NOTES</label><textarea>${x.notes||''}</textarea></div>${metric}${actions}</div>`}
function handleAction(action,id){const x=data.find(y=>y.id===id);if(!x)return;if(action==='archive'){if(!confirm(`Archive this ${x.type==='turn'?'Turn':'Listing'} for ${x.address}?`))return;x.archived=true;x.archivedAt=TODAY;openId=null;save();render();return}if(action==='restore'){if(!confirm(`Restore ${x.address} to the active Whiteboard?`))return;x.archived=false;x.archivedAt='';filter='all';openId=x.id;save();render();return}if(action==='create-listing'){if(!confirm(`Create Listing for ${x.address} and archive this Turn?`))return;const listing={id:Date.now(),address:x.address,type:'listing',archived:false,notes:x.notes||'',price:'',securityDeposit:'',sourceTurnId:x.id,sourceKeysReturned:get(x,'Keys Returned')||'',process:listingProcess()};setVal(listing,'Listed',get(x,'Listed')||'');x.archived=true;x.archivedAt=TODAY;x.linkedListingId=listing.id;data.unshift(listing);filter='all';openId=listing.id;save();render()}}
$('#search').oninput=render;const modal=$('#modal');function showModal(v){modal.classList.toggle('hidden',!v);if(v)$('#newAddress').focus()}$('#newProcess').onclick=()=>showModal(true);$('#closeModal').onclick=$('#cancelModal').onclick=()=>showModal(false);$('#newType').onchange=()=>$('#turnStartFields').style.display=$('#newType').value==='turn'?'grid':'none';$('#newForm').onsubmit=e=>{e.preventDefault();const type=$('#newType').value,x={id:Date.now(),address:$('#newAddress').value.trim(),type,archived:false,notes:$('#newNotes').value.trim(),process:type==='turn'?turnProcess():listingProcess()};if(type==='turn'){setVal(x,'Tenant Gave Notice',$('#newNotice').value);setVal(x,'Move Out',$('#newMove').value)}else{x.price='';x.securityDeposit='';x.sourceKeysReturned=''}data.unshift(x);save();filter='all';openId=x.id;e.target.reset();$('#turnStartFields').style.display='grid';showModal(false);render()};save();render();
